name: Feature Request
description: Suggest an idea for Kiro
labels: ["pending-triage"]
body:
  - type: markdown
    attributes:
      value: |

        ## Before submitting a Feature request, please [search and confirm](https://github.com/kirodotdev/Kiro/issues?q=sort%3Aupdated-desc%20is%3Aissue%20is%3Aopen%20type%3AFeature) that it does not yet exist. Duplicate requests will be closed.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What problem does this solve and how should it work?
      placeholder: "Describe the challenge you're facing and your suggested feature."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: "Provide concrete examples of when and how you'd use this."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant details
      placeholder: "Screenshots, examples, or technical details that might help."
    validations:
      required: false
